modLoader = "javafml"
loaderVersion = "[43,)"
license = "Custom"

[[mods]]
modId = "brewery"
version = "${version}"
displayName = "Brewery"
authors = "BaumeisterJO, satisfy, ECarrascon"
description = '''
O'zapft is! Welcome to Brewery. Establish your own brewery and craft beer and whiskey.
'''
logoFile = "pack.png"

[[dependencies.brewery]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.82,)"
ordering = "AFTER"
side = "BOTH"