modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "brewery"
version = "${version}"
displayName = "Brewery"
authors = "BaumeisterJO, satisfy"
description = '''
O'zapft is! Welcome to Brewery. Establish your own brewery and craft beer and whiskey.
'''
#logoFile = ""

[[dependencies.brewery]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"