modLoader = "javafml"
loaderVersion = "[45,)"
license = "Custom"

[[mods]]
modId = "brewery"
version = "${version}"
displayName = "Brewery"
authors = "BaumeisterJO, satisfy"
description = '''
O'zapft is! Welcome to Brewery. Establish your own brewery and craft beer and whiskey.
'''
logoFile = "pack.png"

[[dependencies.brewery]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"